openapi: '3.0.0'
info:
  title: AWS Management API
  description: An API for a collaborative AWS resource management portal
  version: '1.0.0'

paths:
  /:
    get:
      responses:
        '200':
          description: testing
                            
  /test:
    get:
      responses:
        '200':
          description: Hello world
