name: Backend CI

on:
  push:
    paths:
      - 'backend/*'
  pull_request:
    paths:
      - 'backend/*'
  workflow_dispatch:

jobs:
  tests:
    name: backend tests
    runs-on: ubuntu-latest

  services:
    postgres:
      image: postgres
      env:
        POSTGRES_DB: dev-db
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
      ports:
        - 5432:5432
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5

  steps:
    - name: Repo checkout
      uses: actions/checkout@v4

    - name: Pnpm setup
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Node setup
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      working-directory: ./backend
      run: pnpm run test
