name: Publish Dev DB Docker Image

on:
  push:
    paths:
      - 'db/*'
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push DB (dev) Image to Github Container Registry
    runs-on: ubuntu-latest
      
    permissions:
      contents: read
      packages: write
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: GHCR login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build and Push DB Image
      uses: docker/build-push-action@v2
      with:
        context: ./db
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/tfc-dev-db:latest
