name: Publish Frontend Docker Image

on:
  push:
    paths:
      - 'frontend/*'
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Frontend Image to Github Container Registry
    runs-on: ubuntu-latest
      
    permissions:
      contents: read
      packages: write
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: GHCR login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build and Push DB Image
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./frontend/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/tfc-frontend:latest
